server:
  port: 8080
spring:
  profiles:
    active: mixed
  datasource:
    url: jdbc:mysql://192.168.206.23:30006/springbatch_sample?characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: password
  batch:
    schema: classpath:org/springframework/batch/core/schema-@@platform@@.sql
    initialize-schema: always
    job:
      enabled: false
    table-prefix: BATCH_
  jpa:
    database: mysql
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
partition:
  rabbit:
    host: 192.168.206.23
    port: 32002
    username: admin
    password: lonntec
    virtualHost: /
    connRecvThreads: 1
    channelCacheSize: 1



